function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.8 (R2020a) and Automated Driving Toolbox 3.1 (R2020a).
% Generated on: 06-Sep-2020 23:00:26

%get scenario data
open_system('VehicleFollowing');
sim('VehicleFollowing');

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [700 0 0;
    0 0 0];
road(scenario, roadCenters);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [0 -1.5 0]);
waypoints = [ans.ego_info.InertFrm.Cg.Disp.X.Data ans.ego_info.InertFrm.Cg.Disp.Y.Data ans.ego_info.InertFrm.Cg.Disp.Z.Data];
speed = ans.ego_info.InertFrm.Cg.Vel.Xdot.Data;
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 2, ...
    'Position', [14.5 -1.1 0]);
waypoints = [ans.v1_info.InertFrm.Cg.Disp.X.Data ans.v1_info.InertFrm.Cg.Disp.Y.Data ans.v1_info.InertFrm.Cg.Disp.Z.Data];
speed = ans.v1_info.InertFrm.Cg.Vel.Xdot.Data;
trajectory(car1, waypoints, speed);

