function [scenario, egoVehicle] = createDrivingScenario1()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.8 (R2020a) and Automated Driving Toolbox 3.1 (R2020a).
% Generated on: 07-Sep-2020 22:06:04

%get scenario data
open_system('VehicleFollowing');
sim('VehicleFollowing');
data = ans;
% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    1000 0 0];
laneSpecification = lanespec(3, 'Width', 2.5);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [9.7 -2.5 0]);
    waypoints = [data.ego_info.InertFrm.Cg.Disp.X.Data data.ego_info.InertFrm.Cg.Disp.Y.Data data.ego_info.InertFrm.Cg.Disp.Z.Data];
    speed = sqrt(data.ego_info.InertFrm.Cg.Vel.Xdot.Data.^2+data.ego_info.InertFrm.Cg.Vel.Ydot.Data.^2);
    trajectory(egoVehicle, waypoints, speed);
% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 2, ...
    'Position', [49.8 -2.5 0]);
    waypoints = [data.v1_info.InertFrm.Cg.Disp.X.Data data.v1_info.InertFrm.Cg.Disp.Y.Data data.v1_info.InertFrm.Cg.Disp.Z.Data];
    speed = sqrt(data.v1_info.InertFrm.Cg.Vel.Xdot.Data.^2+data.v1_info.InertFrm.Cg.Vel.Ydot.Data.^2);
    trajectory(car1, waypoints, speed);
car2 = vehicle(scenario, ...
    'ClassID', 3, ...
    'Position', [112.9 -2.5 0]);
    waypoints = [data.v2_info.X.Data data.v2_info.Y.Data data.v2_info.Z.Data];
    speed = sqrt(data.v2_info.xdot.Data.^2+data.v2_info.ydot.Data.^2);
    trajectory(car2, waypoints, speed);
